# Generated by Django 6.1.1 on 2026-09-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='resend_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
